cbvPro3/cbvPro3/urls.py
from django.contrib import admin
from django.urls import path,include
from crudapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('crudapp/', include('crudapp.urls', namespace='crudapp')),
]

cbvPro3/crudapp/urls.py
from django.urls import path
from . import views

app_name = 'crudapp'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    # link to pk of school selected in school_list.html using href of anchor tag
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete')

]

cbvPro3/crudapp/models.py
from django.db import models
from django.urls import reverse


# SuperUserInformation
# User: Ankur
# Email: training@home.com
# Password: testpassword

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    # CreateView -
    # 1) Django CreateView is automatically creating a default html template that is expecting.
    # It is expecting into be in format of all lower case model name (School and then _form)
    # i.e., school_form.html. Always suggest to use default name for template and create school_form.html
    # to add form to create new School.
    # 2) Also, define a get_absolute_url method on the Model (here School). This is linked with CreateView
    # to tell create view where to go after creating a page. Here, go back and reverse and figure out
    # you should go to the detail page for whatever the primary key of school you have just created.
    def get_absolute_url(self):
        return reverse("crudapp:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

cbvPro3/crudapp/views.py
# CRUD (Create, Retreive, Update & Delete) operations using Class Based Views
# Use of TemplateView, ListView, DetailView, CreateView, UpdateView and DeleteView

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, DeleteView,
                                  UpdateView)
from . import models


# Create your views here.
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'


class SchoolListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list' i.e., (lower-case of model name School then _list)

    # Example of making our own:
    # context_object_name = 'schools'
    model = models.School  # here template name not passed. We need to create template as school_list.html
    # to link this view. Using href="{% url 'crudapp:list' %} in anchor tag of crudapp_base.html to call this view.


class SchoolDetailView(DetailView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object
    # Default would be 'school' i.e., (lower-case of model name School only)

    # Example of making our own:
    # context_object_name = 'schools'
    context_object_name = 'school_detail'
    model = models.School
    # Create template name with same name as context_object_name
    template_name = "crudapp/school_detail.html"  # template_name is an attribute from DetailView class.


# CreateView -
# 1) Django CreateView is automatically creating a default html template that is expecting.
# It is expecting into be in format of all lower case model name (School and then _form)
# i.e., school_form.html. Always suggest to use default name for template and create school_form.html
# to add form to create new School.
# 2) Also, define a get_absolute_url method on the Model (here School). This is linked with CreateView to
# tell create view where to go after creating a page. Here, go back and reverse and figure out
# you should go to the detail page for whatever the primary key of school we have just created.
class SchoolCreateView(CreateView):
    fields = ("name", "principal", "location")
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")  # this field will map to form which was created at school_form.html
    # for update
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School  # create form in school_confirm_delete.html for delete
    success_url = reverse_lazy("crudapp:list")  # Once school is deleted call list of school view using reverse_lazy

cbvPro3/crudapp/templates/crudapp/crudapp_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'crudapp:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

cbvPro3/crudapp/templates/crudapp/school_confirm_delete.html
{% extends "crudapp/crudapp_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'crudapp:detail' pk=school.pk %} ">Cancel</a>

</form>

{% endblock %}

cbvPro3/crudapp/templates/crudapp/school_detail.html
{% extends "crudapp/crudapp_base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the School Detail Page</h1>

        <h2>School Details:</h2>
        <p>Id_num: {{school_detail.id}}</p>
        <p>Name: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}}</p>

        <h3>Students:</h3>
        {% for student in school_detail.students.all %}
            <p>{{student.name}} who is {{student.age}} years old.</p>
        {% endfor %}
    </div>

    {# Add Update link using href of anchor tag and call school_detail.html #}
    <div class="container">
        <p><a class='btn btn-warning' href="{% url 'crudapp:update' pk=school_detail.pk %}">Update</a></p>
    </div>
{% endblock %}

cbvPro3/crudapp/templates/crudapp/school_form.html
{% extends "crudapp/crudapp_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
    Create School
  {% else %}
    Update School
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

cbvPro3/crudapp/templates/crudapp/school_list.html
{% extends "crudapp/crudapp_base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the List of Schools Page!</h1>
            <ol>
                {% for school in school_list %}
                    {# Add pk school.id in href so that this will link to app urls.py Detail view page #}
                    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
                {% endfor %}
            </ol>
    </div>

{% endblock %}

cbvPro3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'crudapp:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

cbvPro3/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}